export interface subscriptiontypes{
id:number,
  name:string,
    monthlyPrice:number,
    yearlyPrice:number,
    description:string,
    features:string[],
}

export const  subscriptionTiers:subscriptiontypes[] = [
    {id:1,
      name: "Starter",
      monthlyPrice: 29,
      yearlyPrice: 349,  
      description: "Best option for personal use & for your next project.",
      features: [
        "Individual configuration",
        "No setup, or hidden fees",
        "Team size: 1 developer",
        "Premium support: 6 months",
        "Free updates: 6 months",
      ],
    },
    {id:2,
      name: "Company",
      monthlyPrice: 99,
      yearlyPrice: 1188, 
      description: "Relevant for multiple users, extended & premium support.",
      features: [
        "Individual configuration",
        "No setup, or hidden fees",
        "Team size: 10 developers",
        "Premium support: 24 months",
        "Free updates: 24 months",
      ],
    },
    {id:3,
      name: "Enterprise",
      monthlyPrice: 499,
      yearlyPrice: 5988,  
      description: "Best for large scale uses and extended redistribution rights.",
      features: [
        "Individual configuration",
        "No setup, or hidden fees",
        "Team size: 100+ developers",
        "Premium support: 36 months",
        "Free updates: 36 months",
      ],
    },
  ];